# This is a basic workflow to help you get started with Actions

name: hello word

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3

      - name: Run app.js
        run: node app

